name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'html/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'html/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
        cd html
        docker build . --file Dockerfile --tag ghcr.io/bokamatyas/html-test-agv:$IMAGE_TAG
        docker login ghcr.io --username bokamatyas --password ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/bokamatyas/html-test-agv:0.1
